#150 wait for Pantheon deployment
Lullabot/drainpipe pull request #395
Opened 2024-02-05 16:59 UTC by beto-aveiga

2024-02-08 17:26 UTC, mrdavidburns commented
@beto-aveiga I believe we have the [Test GitHub Actions](https://github.com/Lullabot/drainpipe/actions/workflows/TestGitHubActions.yml) workflow doing this for us.

Here's an example build that passed where it builds and pushes to Pantheon MultiDev.
https://github.com/Lullabot/drainpipe/actions/runs/7831957935/job/21373672972#step:15:1

We may still want to check out this branch on a project where we've had this job flaky failing due to MultiDev timeouts. Ping me in Slack and I'll let you know which project that is.

2024-02-09 15:48 UTC, justafish commented on scaffold/github/actions/pantheon/review/action.yml
> +        TIMEOUT=$((5 * 60))  # 5 minutes in seconds
let's leave this as 30s

2024-02-12 14:30 UTC, deviantintegral requested changes
Please see my comment at https://github.com/Lullabot/drainpipe/issues/159#issuecomment-1491842864 as this is still fragile if deployments take longer than 5 minutes. Terminus has a plugin command we can use that handles all of the waiting and retry logic for us.

2024-02-14 20:29 UTC, beto-aveiga commented
> Please see my comment at [#159 (comment)](https://github.com/Lullabot/drainpipe/issues/159#issuecomment-1491842864) as this is still fragile if deployments take longer than 5 minutes. Terminus has a plugin command we can use that handles all of the waiting and retry logic for us.

I will work on it. Thanks!

2024-02-14 21:53 UTC, mrdavidburns commented
Looks like the version of Drush we're running might not have the command that @deviantintegral suggested.
```
  There are no commands defined in the "build:workflow" namespace.  


Failed to execute command terminus build:workflow:wait ***: exit status 1
```

2024-02-15 11:23 UTC, justafish commented on scaffold/github/actions/pantheon/review/action.yml
> +        drainpipe_exec "terminus workflow:wait pantheon-pr-${{DRAINPIPE_PR_NUMBER}}"
```suggestion
        drainpipe_exec "terminus workflow:wait ${{ inputs.site-name }}.pr-$DRAINPIPE_PR_NUMBER"
```

2024-02-15 11:29 UTC, merged