Pull gitlab / github installer code into new methods
Lullabot/drainpipe pull request #533
Opened 2024-04-16 19:50 UTC by deviantintegral

This PR pulls is the first two commits from https://github.com/Lullabot/drainpipe/pull/114/commits that:

1. Extracts private methods to reduce the length of the installCiCommands method.
2. Adds an early return to manage some of the intense nesting the code currently has.

2024-04-17 09:55 UTC, justafish commented
[nesting intensifies]

2024-04-17 11:37 UTC, justafish requested changes
@deviantintegral I fixed the database version error mismatch, which I thought was a result of a DDEV upgrade. I think the test failures are now genuine however as the Tugboat files don't seem to be be installed correctly.

2024-04-25 20:57 UTC, davereid commented on scaffold/pantheon/pantheon.yml
> +  version: 10.11
How do we feel about this change going out to all sites? Does this upgrade to several versions work okay on Pantheon deployments?

2024-04-25 21:03 UTC, davereid commented on scaffold/pantheon/pantheon.yml
> +  version: 10.11
I feel like I don't see 10.11 listed on https://docs.pantheon.io/pantheon-yml#specify-a-version-of-mariadb so does this need to be 10.6?

2024-07-19 15:00 UTC, merged