ISSUE-220: replace using npx to execute action-validator, use the binary instead
Lullabot/drainpipe pull request #576
Opened 2024-05-16 22:41 UTC by beto-aveiga

### Description
- Dowloads the binary of action-validator instead of using `npx`.

2024-05-22 21:26 UTC, justafish requested changes
Thanks for the PR. This would download the binary each time the task is run, instead could you please change it to use the the same installation method as we use for task and the local security checker e.g.
https://github.com/Lullabot/drainpipe/blob/main/src/BinaryInstaller.php
https://github.com/Lullabot/drainpipe/blob/main/drainpipe-dev/src/DevBinaryInstallerPlugin.php

2024-05-27 15:03 UTC, beto-aveiga commented
@justafish I noticed that `action-validator` is only available for
- linux amd64
- linux arm64
- darwin amd64
- darwin arm64

Is that something we need to worry about? Or do something different in the binary installer? Or fallback to `npx` when the binary is not found?

2024-05-27 15:56 UTC, beto-aveiga commented
I just added a fallback in case the binary is not available.

2024-05-28 20:32 UTC, deviantintegral commented
> I just added a fallback in case the binary is not available.

That would be if you were running on Windows, directly on the host? Do we actually support doing that? @justafish thoughts?

If we keep it, I think we should document that it's specifically for Windows support as a comment.

2024-06-05 11:29 UTC, justafish commented on tasks/github.yml
> +          fi
```suggestion
          if [ -f ./vendor/bin/action-validator ]; then
              find $directories -type f \( -iname '*.yaml' -o -iname '*.yml' \) | xargs -n1 ./vendor/bin/action-validator
          else
              find $directories -type f \( -iname '*.yaml' -o -iname '*.yml' \) | xargs -n1 npx @action-validator/cli
          fi
```

2024-06-05 11:30 UTC, justafish commented on tasks/github.yml
> +          else
```suggestion
          # Fallback for architectures that don't have a release e.g. Windows
          else
```

2024-06-05 11:31 UTC, justafish commented on tasks/github.yml
> +          # Fallback for architectures that don't have a release e.g. Windows
```suggestion
```

2024-06-05 11:35 UTC, justafish approved these changes
I added a minor tweak to the explicit path of the binary, and added Andrew's suggestion for a comment. I've tested this locally with the drainpipe-test script and all looks to be working well :+1: 

Thanks all!

2024-06-05 13:05 UTC, merged