Add SASS Glob
Lullabot/drainpipe pull request #78
Opened 2022-03-09 18:32 UTC by ckrina

2022-03-11 09:42 UTC, justafish requested changes
Great idea!

Could you add something in the README about this?

Looks like you've accidentally checked in your IntelliJ config

2022-03-15 14:25 UTC, ckrina commented
@justafish I might have gone too far with documentation, but I think that's what I would need to understand it. But happy to change anything!

2022-03-15 14:30 UTC, justafish approved these changes

2022-03-15 14:30 UTC, justafish commented on README.md
> +submodules SASS and Javascript.
```suggestion
Drainpipe provides tasks to automate Sass & JavaScript compilation.
```

2022-03-15 14:30 UTC, justafish commented on README.md
> +- `ddev task assets:watch` Task to watch and build the changes while working on the theme.
```suggestion
You can then run the following tasks:
- `ddev task assets` Default task to compile the CSS and JS once for production.
- `ddev task assets:watch` Task to watch and build the changes while working on the theme.
```

2022-03-15 14:36 UTC, merged